name: Check OpenGL

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Setup llvmpipe
        run: |
          tar -zxf mesa-18.2.3.tar.gz
          export LD_LIBRARY_PATH=mesa-18.2.3/usr/local/lib/x86_64-linux-gnu
          export GALLIUM_DRIVER=swr
          sudo apt-get install mesa-utils
          sudo apt-get install xvfb
          xvfb-run glxinfo
      - name: Build with Gradle
        run: ./gradlew jar
      - name: Run OPENRNDR application
        run: xvfb-run java -jar build/libs/application-linux-x64.jar
      - uses: ncipollo/release-action@v1.6.1
        name: Upload screenshot to release
        id: create_release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          replaceArtifacts: false
          body: Fully automated release
          artifacts: "result.png"