name: Check OpenGL

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build llvmpipe
        run: |
          sudo apt-get install llvm-dev bison flex
          wget https://mesa.freedesktop.org/archive/mesa-20.0.5.tar.xz
          tar -xf mesa-20.0.5.tar.xz
          sudo pip3 install setuptools
          sudo pip3 install wheel
          sudo pip3 install meson
          cd mesa-20.0.5
          mkdir build
          cd build
          meson -D glx=disabled -D gallium-drivers=swrast -D egl=auto  -D platforms=surfaceless 
          ninja
