name: Check OpenGL

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build llvmpipe
        run: |
          sudo apt-get install llvm-dev
          wget https://mesa.freedesktop.org/archive/mesa-20.0.5.tar.xz
          tar -xf mesa-20.0.5.tar.xz
          pip3 install setuptools --user
          pip3 install meson --user
          cd mesa-20.0.5
          mkdir build
          cd build
          meson -D glx=gallium-xlib -D gallium-drivers=swrast
          ninja
